[package]
name = "key-driver"
version = "0.1.0"
authors = ["Bradley Gannon <bradley@bradleygannon.com>"]
edition = "2021"

[[bin]]
name = "key-driver"
test = false
bench = false

[dependencies]
avr-device = { version = "0.8.1", features = ["atmega328p", "rt"] }
panic-halt = "1.0.0"
ufmt = "0.2.0"
nb = "1.1.0"
embedded-hal = "1.0"
common = { path = "../common" }
heapless = "0.7.17"

[dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "e5c8f37fe48419956e722490a82b9ca9b9fc61a2"
features = ["arduino-nano"]

[dependencies.atmega-hal]
git = "https://github.com/rahix/avr-hal"
rev = "e5c8f37fe48419956e722490a82b9ca9b9fc61a2"
features = ["atmega328p"]

[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"
