[package]
name = "controller"
version = "0.1.0"
authors = ["Bradley Gannon <bradley@bradleygannon.com>"]
edition = "2021"

[[bin]]
name = "controller"
test = false
doctest = false
bench = false

[dependencies]
cortex-m = "0.7.7"
embedded-hal = "1.0.0"
fugit = "0.3.7"
log = "0.4.27"
midi-convert = "0.2.0"
teensy4-panic = "0.2.3"
usbd-midi = "0.5.0"
usbd-serial = "0.2.2"
usb-device = { version = "0.3.2", features = ["control-buffer-256"] }

[dependencies.teensy4-bsp]
git = "https://github.com/bmgxyz/teensy4-rs"
branch = "bump-hal"
features = ["rt"]

[profile.dev]
# Without these changes, the code is too slow and panics after a few notes
opt-level = 3
overflow-checks = false
